
INSERT INTO `country` VALUES (1,'Brasil','BRL');

INSERT INTO `state_province` VALUES(1, 1, 'Acre');
INSERT INTO `state_province` VALUES(2, 1, 'Alagoas');
INSERT INTO `state_province` VALUES(3, 1, 'Amazonas');
INSERT INTO `state_province` VALUES(4, 1, 'Amapá');
INSERT INTO `state_province` VALUES(5, 1, 'Bahia');
INSERT INTO `state_province` VALUES(6, 1, 'Ceará');
INSERT INTO `state_province` VALUES(7, 1, 'Distrito Federal');
INSERT INTO `state_province` VALUES(8, 1, 'Espírito Santo');
INSERT INTO `state_province` VALUES(9, 1, 'Goiás');
INSERT INTO `state_province` VALUES(10, 1, 'Maranhão');
INSERT INTO `state_province` VALUES(11, 1, 'Minas Gerais');
INSERT INTO `state_province` VALUES(12, 1, 'Mato Grosso do Sul');
INSERT INTO `state_province` VALUES(13, 1, 'Mato Grosso');
INSERT INTO `state_province` VALUES(14, 1, 'Pará');
INSERT INTO `state_province` VALUES(15, 1, 'Paraíba');
INSERT INTO `state_province` VALUES(16, 1, 'Pernambuco');
INSERT INTO `state_province` VALUES(17, 1, 'Piauí');
INSERT INTO `state_province` VALUES(18, 1, 'Paraná');
INSERT INTO `state_province` VALUES(19, 1, 'Rio de Janeiro');
INSERT INTO `state_province` VALUES(20, 1, 'Rio Grande do Norte');
INSERT INTO `state_province` VALUES(21, 1, 'Rondônia');
INSERT INTO `state_province` VALUES(22, 1, 'Roraima');
INSERT INTO `state_province` VALUES(23, 1, 'Rio Grande do Sul');
INSERT INTO `state_province` VALUES(24, 1, 'Santa Catarina');
INSERT INTO `state_province` VALUES(25, 1, 'Sergipe');
INSERT INTO `state_province` VALUES(26, 1, 'São Paulo');
INSERT INTO `state_province` VALUES(27, 1, 'Tocantins');
